podTemplate(containers: [
  containerTemplate(
    name: 'gradle',
    image: 'gradle:6.3-jdk14',
    command: 'sleep',
    args: '30d'
    ),
  ]) {
    node(POD_LABEL) {
      stage('Run pipeline against a gradle project - test MAIN') {
	container('gradle') {
          stage('Build a gradle project') {
            echo "I am the ${env.BRANCH_NAME} branch"
            sh '''
            pwd
	    ls -l
            chmod +x gradlew
            ./gradlew test
            '''
          }
          stage('Code coverage') {
	          sh 'printenv'
            echo "My CC branch is: ${env.CHANGE_BRANCH}"
            if (env.BRANCH_NAME == "main") {
              echo "I am the ${env.BRANCH_NAME} branch"
              sh '''
              pwd
              ./gradelew jacocoTestCoverageVerification
              ./gradlew jacocoTestReport
              '''

              // from the HTML publisher plugin
              // https://www.jenkins.io/doc/pipeline/steps/htmlpublisher/
              publishHTML (target: [
                reportDir: 'build/reports/tests/test',
                reportFiles: 'index.html',
                reportName: "JaCoCo Report"
              ])
            }
          }
          stage("Checkstyle") {
            try {
              sh '''
              pwd
              ./gradlew checkstyleMain
              '''
              } catch (Exception E) {
                echo 'Failure detected'
              }
                    
            publishHTML (target: [
            reportDir: 'build/reports/tests/test',
            reportFiles: 'index.html',
            reportName: "JaCoCo checkstyle"
            ])  
          }
        }
      }   
    }
}
